//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flow()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IssueType_Id { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual IssueType IssueType { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
