//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> Request_Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
