//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Flow_Id { get; set; }
        public string Details { get; set; }
        public Nullable<int> Status_Id { get; set; }
    
        public virtual Flow Flow { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Status Status { get; set; }
    }
}
